[package]
name = "ni-usb-6259"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.6.1"
thiserror = "1.0.58"
tracing = "0.1.37"

[build-dependencies]
bindgen = "0.66.1"
